//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCrawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactUsData
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> SubmittedTime { get; set; }
        public Nullable<bool> Seen { get; set; }
        public Nullable<System.DateTime> SeenTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
