//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practicing_OAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomTable
    {
        public int Id { get; set; }
        public bool CustomField { get; set; }
        public string Signatures { get; set; }
        public string Password { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Added_At { get; set; }
        public string CustomField1 { get; set; }
        public string CustomField2 { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}
