//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practicing_OAuth.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ProductsReview
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }

        [DisplayName("Submitted By")]
        public string ReviewerName { get; set; }
        public string Review { get; set; }
        public Nullable<int> Rating { get; set; }

        [DisplayName("Submitted At")]
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
